CREATE DATABASE IF NOT EXISTS labdb;

USE labdb;

CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);

CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'apppass';

GRANT SELECT, INSERT, UPDATE, DELETE ON labdb.* TO 'appuser'@'%';

FLUSH PRIVILEGES;